#!/usr/bin/env python3
"""Regenerate search-index.js from the current content of the week pages.

Run this after editing any subsection title or body text so site search
stays in sync:

    python3 build_search_index.py
"""
import json
import re
from bs4 import BeautifulSoup

PAGES = ["index.html", "week2.html", "week3.html", "week4.html", "week5.html"]


def clean(text):
    return re.sub(r"\s+", " ", text).strip()


def extract(soup, page):
    label_el = soup.find("h1")
    label = clean(label_el.get_text()) if label_el else page
    out = []
    for sub in soup.select("details.sub[id]"):
        h3 = sub.select_one("summary h3")
        content = sub.select_one(".sub-content")
        if not h3 or not content:
            continue
        out.append({
            "page": page, "pageLabel": label, "id": sub.get("id"),
            "title": clean(h3.get_text()), "body": clean(content.get_text()),
        })
    for day in soup.select("details.day[id]"):
        h2 = day.select_one("summary h2")
        body = day.select_one(".day-body")
        if not h2 or not body:
            continue
        body_copy = BeautifulSoup(str(body), "html.parser")
        for s in body_copy.select("details.sub"):
            s.decompose()
        out.append({
            "page": page, "pageLabel": label, "id": day.get("id"),
            "title": clean(h2.get_text()), "body": clean(body_copy.get_text()),
        })
    return out


def main():
    all_entries = []
    for page in PAGES:
        with open(page, encoding="utf-8") as f:
            soup = BeautifulSoup(f.read(), "html.parser")
        all_entries.extend(extract(soup, page))
    with open("search-index.js", "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_search_index.py -- do not hand-edit.\n")
        f.write("// Regenerate after changing any subsection title/body text.\n")
        f.write("window.SEARCH_INDEX = ")
        f.write(json.dumps(all_entries, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print(f"Wrote search-index.js with {len(all_entries)} entries")


if __name__ == "__main__":
    main()
